spring:
  application:
    name: invoice-rules-api
  profiles:
    active: prod

springdoc:
  api-docs:
    path: /api-docs
    groups.enabled: true
  swagger-ui:
    path: /docs
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    doc-expansion: none